export const creators = [
  "KORG",
  "Focusrite",
  "Kilohearts",
  "Voxengo",
  "Arturia",
  "Waves",
  "keilwerthAudio",
  "Baby Audio",
  "iZotope",
  "Accusonus",
  "Antares",
  "Teragon Audio",
  "Plugin Alliance",
  "D16 Group",
  "Output",
  "A.O.M.",
  "Sugar Bytes",
  "Toontrack",
  "Universal Audio",
  "TAL-Togu Audio Line",
  "reFX",
  "Splice",
  "XLN Audio",
  "Cableguys",
  "Apple",
  "Akai",
  "Image-Line",
  "Applied Acoustics Systems",
  "Slate Digital",
  "Goodhertz",
  "Flux",
  "Blue Cat Audio",
  "SoundToys",
  "Audio Ease",
  "FabFilter",
  "Tone2",
  "Exponential Audio",
  "HOFA",
  "Sonalksis",
  "u-he",
  "PSPaudioware",
  "ArtsAcoustic",
  "Native Instruments",
  "Sample Magic",
  "Dev code",
  "Thomas Mundt",
  "ERS",
  "Dmitry Sches",
  "Softube",
  "East West",
  "Matt Tytel",
  "Ignite Amps",
  "Valhalla DSP",
  "Xfer Records",
  "Sonic Academy",
  "AlyJamesLab",
  "Illformed",
  "Adam Szabo",
  "Waldorf",
  "Glitchmachines",
  "Ohm Force",
  "TC Electronic",
  "AudioSpillage",
  "Sound Magic",
  "Steinberg",
  "McDSP",
  "lkjb",
  "Cakewalk",
  "4Front Technologies",
  "LVC-Audio",
  "Studiolinked VST",
  "Plug and Mix",
  "MetaFunction",
  "Sinevibes",
  "KV331Audio",
  "Bitwig",
  "Wavesfactory",
  "Spectrasonics",
  "FutureAudioWorkshop",
  "IK Multimedia",
  "Reveal Sound",
  "ROLI",
  "Vember Audio",
  "Lexicon",
  "Synapse",
  "Rob Papen",
  "Mathew Lane",
  "Camel Audio",
  "Ableton",
  "Plugin Boutique",
  "Minimal Audio",
  "Sonic Charge",
  "Access",
  "Seven Phases",
  "Aglae Software",
  "Intelligent Sounds & Music",
  "WaveDNA",
  "Cytomic",
  "Dada Life",
  "Celemony",
];
